version: '3.1'
services:
  app:
    image: openjdk
    build: .
    volumes:
      - var/bin
    depends_on:
      - mysql
    ports:
      - "8080:9000"
    restart: always
    environment:
      - name=value
  user: root
  mysql:
    image: mysql:lates
    environment:
      - MYSQL_USERNAME=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    ports:
      -"3000:3306"

secrets:
  file_secret:
     file: ./secret.txt

  
  
               